#
# CALCULATE ODDS RATIOS FUNCTION
#
#
# Function used to combined location and feature specifc phenotype scores according to weightings
#
# - passes data.frame containing score summary generated by scorePhenotype, data.frame containing weights for calculating combined score
# -creates various scoring columns according to arguments passed
# - returns data.frame with new score columns
#
# arguments:
#   input - data.frame containing subset of phenotypic data to be analyzed
#   recodeValues - data.frame containing phenotype ID with associated values (values according to severity of phenotypic classification)
#   featureMapping - data.frame containing feature  and associated weightings (according to regions associated with greater disease severity)
#
# return:
#   output - data.frame containing new score values

library(dplyr)
library(epitools)

compileOddsRatioData <- function(dataSet, caseControlCond, covarList)
{
  
  oddsRatioList <- lapply(covarList, function(y){
    
    contig <- calculateContigencyTable(dataSet[,c(caseControlCond,y)],caseControlCond,y)
    oddsSet <- extractOddsData(contig)
    
    return(oddsSet)
    
  })
  
  oddsRatioDF <- bind_rows(oddsRatioList)
  
  return(oddsRatioDF)
}

extractOddsData <- function(oddsData)
{
  
  datadf <- oddsData[[1]]
  ORdf <- oddsData[[2]]
  pvaldf <- oddsData[[3]]
  

  
  disease <- names(dimnames(datadf))[2]
  name <- names(dimnames(ORdf))[1]
  
  OR <- ORdf[2,1]
  LCI <- ORdf[2,2]
  UCI <- ORdf[2,3]
  
  newOddsData <- data.frame(Disease=disease,Exposure=name,Odds_Ratio=OR,LCI=LCI,UCI=UCI,stringsAsFactors=FALSE)
  
  colnames(newOddsData) <- c("Disease","Exposure","Odds Ratio","Lower 95% CI","Upper 95% CI")
  
  return(newOddsData)
  
}

calculateContigencyTable <- function(data, caseControlCond, covar)
{
  summarizedDataInclNA <- data %>%
    group_by_(.dots = c(caseControlCond, covar)) %>%
    tally()
  
  summarizedData <- data %>%
    filter(AffStatus != 0)  %>%
    group_by_(.dots = c(caseControlCond, covar))
  
  contigTable <- table(summarizedData)
  
  contigTrans <- t(contigTable)
  
  
  oddsData <- calculateOddsRatio(contigTrans)
  
  return(oddsData)
}

calculateOddsRatio <- function(contigTable)
{
  oddsRatio <- oddsratio.fisher(contigTable, NULL)

  return(oddsRatio)
  
}

#prunedData <- data %>%
#  filter_(.dots = paste0("!is.na(",caseControlCond, ")"))

#print(prunedData)
