#
# CATEGORY TO DOSAGE FUNCTION
#
#
# Function to convery category columns generated by categoryMutate into dosage values according to dosageMap.  Also calculates combined dosage score
# for column grouping passed
#
# - passes data.frame containing dataset, indices of the columns to be categorized, and dosage hash table
# - creates one new column for each column categorized plus columns for combined dosage, 
# - returns data.frame with new columns insert after categorized columns
#
# arguments:
#   dataSet - data.frame containing category columns
#   indices - vector of columns indices to be converted
#   dosageHash - hash table containing category keys and associated dosage values
#
# return:
#   output - data.frame containg dataSet with new category columns

source("categorize.R")  #include source for categorize function

categoryToDosage <- function(dataSet,indices,dosageHash)
{
  
  temp <- apply(dataSet[indices],c(1,2), function(x){
    t <- categorize(as.character(x),dosageHash)
    return(t)
  })
  
  colnames(temp) <- paste(colnames(temp),"Dosage", sep=" ")
  print(temp)
  
  
  combined <- apply(temp,2,function(x){
    
    if(!any(sapply(temp,class)=="character"))
    {
      
      return(sum(x))
      
    }
    else
    {
      return("NoVal")
    }
  
    })
  
  print(combined)
  
  temp <- cbind(temp,combined)
  dataSet <- cbind(dataSet,temp)

  return(dataSet)
}

test <- read.csv("test2.csv", stringsAsFactors = FALSE)
categoryHashtest <- data.frame(c("Test1","Test2","Z"),c(1,2,3),stringsAsFactors = FALSE)
test2 <- categoryToDosage(test2,c(7,8),categoryHashtest)