#
# CATEGORY TO DOSAGE FUNCTION
#
#
# Function to convery category columns generated by categoryMutate into dosage values according to dosageMap.  Also calculates combined dosage score
# for column grouping passed
#
# - passes data.frame containing dataset, indices of the columns to be categorized, and dosage hash table
# - creates one new column for each column categorized plus columns for combined dosage, 
# - returns data.frame with new columns insert after categorized columns
#
# arguments:
#   data_set - data.frame containing category columns
#   indices - vector of columns indices to be converted
#   hash_dosage - hash table containing category keys and associated dosage values
#
# return:
#   output - data.frame containg data_set with new category columns

source("categorize.R")  #include source for categorize function

categoryToDosage <- function(data_set, indices, hash_dosage)
{
  data_dosage <- apply(data_set[indices], c(1, 2), function(x) {
    t <- categorize(as.character(x), hash_dosage)
    return(t)
  })
  
  colnames(data_dosage) <- paste(colnames(data_dosage), "Dosage", sep = " ")
  
  if(ncol(data_dosage)>1)
  {
  combined <- as.data.frame(rowSums(data_dosage, na.rm = TRUE))
  combined_frac <-
    as.data.frame(combined / (max(hash_dosage[, 2], na.rm = TRUE) * length(indices)))
  
  colnames(combined) <-
    paste(paste(colnames(data_dosage), collapse = '+'), "Combined", sep = " ")
  colnames(combined_frac) <-
    paste(paste(colnames(data_dosage), collapse = '+'), "Combined Fraction", sep =
            " ")
  
  data_dosage <- cbind(data_dosage, combined)
  data_dosage <- cbind(data_dosage, combined_frac)
}
  data_set <- cbind(data_set, data_dosage)
  
  return(data_set)
}
