#
# SCORE PHENOTYPIC MODEL FUNCTION
#
#
# Function used to combined location and feature specifc phenotype scores according to weightings
#
# - passes data.frame containing score summary generated by scorePhenotype, data.frame containing weights for calculating combined score
# -creates various scoring columns according to arguments passed
# - returns data.frame with new score columns
#
# arguments:
#   input - data.frame containing subset of phenotypic data to be analyzed
#   recodeValues - data.frame containing phenotype ID with associated values (values according to severity of phenotypic classification)
#   featureMapping - data.frame containing feature  and associated weightings (according to regions associated with greater disease severity)
#
# return:
#   output - data.frame containing new score values

library(dplyr)
scoreModelPhenotype <- function(scoreSummary,weights)
{

  scoreModel <-
    scoreSummary %>%
    select(.,contains("Sum")) %>%
    mutate(modelUnweighted = sum(.)) %>%
    select(.,contains("model")) 
  
  return(scoreModel)
  
}